### ISSUE TITLE
Security vulnerability in the latest version

### ISSUE THREAD

**Issue by 6en6ar** [tjtelan/git-url-parse-rs#51]
Hey Tj Telan,

Is there a way for You to contact me regarding a security vulnerability I discovered, so I can report it to You privately, or if You can give me your contact.

Thank You

**Comment by tjtelan** [comment]
Hi @6en6ar, thanks for bringing a security vulnerability to my attention.

While I understand your initial request to discuss it privately, I encourage you to share the specifics openly within the issue. If you have any specific reasons for wanting to discuss privately, please let me know.

In order to address it effectively, it would be really helpful if you could provide more details directly in the GitHub issue. This way, we can have a clear understanding of the issue and work towards finding a solution together.

**Comment by 6en6ar** [comment]
Hey. Thank You for responding. 

The regex "^\S+(@)\S+(:).*$" on line 396. in lib.rs that searches for the file or ssh scheme inside an url is vulnerable to a Regex denial of service attack when a malicious input is provided to the nomalize_url function. Continuous searching for @ and : when a large input is provided causes the function to hang and the error out. 

The payload I used was: 
std::iter::repeat("g@1::::").take(5000).collect::<String>();
std::iter::repeat(":").take(5000).collect::<String>();

**Comment by alexanderkjall** [comment]
Sorry for the necro of this old thread, but I was trying to reproduce the security problem here with the following code:

```
$ cat Cargo.toml
[package]
name = "git-url-repro"
version = "0.1.0"
edition = "2024"

[dependencies]
git-url-parse = "=0.4.4"
itertools = "0.14"
```
and:
```
$ cat src/main.rs
use itertools::Itertools;

fn main() {
   let _ = git_url_parse::normalize_url(&std::iter::repeat("g@1::::").take(5000).join(""));
}
```

It doesn't take a long time:
```
$ time cargo run
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/git-url-repro`

real	0m0,051s
user	0m0,027s
sys	0m0,024s
```

And playing with the 5000 number gives a roughly linear progression.

Could it be that the security hole was fixed in a dependency somewhere else?
